import { Inter } from 'next/font/google'
import './globals.css'
import {useLocale} from "next-intl";
import {notFound} from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {
  const local = useLocale();
  if(params.local !== local) {
    notFound();
  }

  return (
    <html lang={local}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
